//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebinarManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webinar
    {
        public int Webid { get; set; }
        public string Webname { get; set; }
        public string Webdate { get; set; }
        public string Webtime { get; set; }
        public int Webfees { get; set; }
        public string Webimages { get; set; }
        public Nullable<int> Webdiscount { get; set; }
        public string Webabout { get; set; }
    }
}
